public class CanNames
{
    /*
     * first name, last name, nickname, and filename of image file.
     */
    private static String[][] namesListFaculty =
            {       {"Gary",        "Porper",   "Gary",         "Porper.jpg"},
                    {"Michelle",    "Gallivan", "Michelle",     "Gallivan.jpg"},
                    {"John",        "Sloyan",   "John",         "Sloyan.jpg"},
                    {"Eric",        "Eads",     "Eric",         "Eads.jpg"},
                    {"Jaime",       "Garzon",   "Jaime",        "Garzon.jpg"},
                    {"Regina",      "Sullivan", "Regina",       "Sullivan.jpg" },
                    {"Brett",       "Thibault", "Grett",        "Thibault-B.jpg" },
                    {"Robert",      "Simms",    "Robert",       "Simms.jpg" },
                    {"David",       "Roth",     "David",        "Roth.jpg" },
                    {"Brian",       "Arnold",   "Brian",        "Arnold.jpg"},
                    {"Dominic",     "Vitale",   "Dom",          "Vitale.jpg"},
                    {"Ellen",       "Tyrell",   "Ellen",        "Tyrell.jpg"},
                    {"Dominic",     "Wakeman",  "Dom",          "Wakeman.jpg"},
                    {"Josiann",     "Trainor",  "Josi",         "Trainor.jpg"},
                    {"Jess",        "Thibault", "Jess",         "Thibault-J.jpg"},
                    {"Bret",        "Thibault", "Bret",         "Thibault-B.jpg"},
                    {"Laura",       "Stephens", "Laura",        "Stephens.jpg"},
                    {"Carol",       "Smith-Nichols", "Carol",   "Smith.jpg"},
                    {"Aurora",      "Santangelo",   "Aurora",   "Santangelo.jpg"},
                    {"Tonya",       "Robison",   "Tonya",       "Robison.jpg"},
                    {"Teri",        "Newman",   "Teri",         "Newman.jpg"},
                    {"Tara",        "McGann",   "Tara",         "McGann1.jpg"},
                    {"Erin",        "Mariano",  "Erin",         "Mariano.jpg"},
                    {"Debbi",       "Lehr",     "Debbi",        "Lehr.jpg"},
                    {"Rob",         "Lamb",     "Rob",          "Lamb.jpg"},
                    {"Jennifer",    "Kuehn",    "Jen",          "Kuehn-J.jpg"},
                    {"David",       "Kuehn",    "Dave",         "Kuehn-D.jpg"},
                    {"Christine",   "Kratzer",  "Christine",    "Kratzer.jpg"},
                    {"Melissa",     "Kirkwood", "Melissa",      "Kirkwood.jpg"},
                    {"Courtney",    "Kiely",    "Courtney",     "Kiely.jpg"},
                    {"Elizabeth",   "Kenney",   "Elizabeth",    "Tammaro.jpg"},
                    {"Don",         "Johnston", "Don",          "Johnston1.jpg"},
                    {"Jay",         "Howard",   "Jay",          "Howard.jpg"},
                    {"Derek",       "Fitzpatrick",  "Derek",    "Fitzpatrick.jpg"},
                    {"Anthony",     "Farnsworth",   "Anthony",  "Farnsworth.jpg"},
                    {"Anna",        "Espinosa", "Anna",         "Espinosa.jpg"},
                    {"Emily",       "Dolan",    "Emily",        "Dolan.jpg"},
                    {"Michael",     "Cvetich",  "Mr. C",        "Cvetich.jpg"},
                    {"Gary",        "Brown",    "Gary",         "Brown.jpg"},
                    {"Vanelda",     "Bratt",    "Vanelda",      "Bratt.jpg"},
                    {"Raymond",     "Bratt",    "Ray",          "Bratt-R.jpg"},
                    {"Nicole",      "Ashton",   "Nicole",       "Ashton.jpg"},

            };

    /*
     * getNumNames()
     * Just that.  How many 1D arrays there are in namesList.
     */
    public static int getNumNames()
    {
        return namesListFaculty.length;
    }

    /*
     * getCandInfo()
     * Return the array of strings corresponding to the candidate's info at this index
     */
    public static String[] getCandInfo(int index)
    {
        return namesListFaculty[index];
    }

    private static String[][] namesListStudents = {
            {"Caleb", "Briggs", "Caleb", "CalebBriggs.jpg"},
            {"Jared", "Briggs", "Jared", "JaredBriggs.jpg"},
            {"Arabella", "Cullen", "Bella", "ArabellaCullen.jpg"},
            {"Brandon", "Lillaney", "Brandon", "BrandonLillaney.jpg"},
            {"Flynn", "Lundeen", "Flynn", "FlynnLundeen.jpg"},
            {"Nathaniel", "Mulvaney", "Nate", "NathanielMulvaney.jpg"},
            {"Gilbert", "Patterson", "Gil", "GilbertPatterson.jpg"},
            {"Alexander", "Power", "Toby", "AlexanderPower.jpg"},
            {"Daria", "Prewitt", "Daria", "DariaPrewitt.jpg"},
            {"Austin", "Schler", "Austin", "AustinSchler.jpg"},
            {"Aidan", "Adams", "Aidan", "AidanAdams.jpg"},
            {"Anna", "Hardacre", "Anna", "AnnaHardacre.jpg"},
            {"Elizabeth", "Mulvaney", "Libby", "ElizabethMulvaney.jpg"},
            {"Vidhi", "Pandit", "Vidhi", "VidhiPandit.jpg"},
            {"Misha", "Verma", "Misha", "MishaVerma.jpg"},
            {"Lillian", "Ferrel", "Lilli", "LillianFerrel.jpg"},
            {"Madeline", "Dutton", "Maddy", "MadelineDutton.jpg"},
            {"Samantha", "Kenyherz", "Sam", "SamanthanKenyherz.jpg"},
            {"Griffin", "Lovato", "Griffin", "GriffinLovato.jpg"},
            {"Logan", "Reeves", "Logan", "LoganReeves.jpg"},
            {"Kevin", "Lu", "Kevin", "KevinLu.jpg"},
            {"Helena", "Yuan", "Helena", "HelenaYuan.jpg"},
            {"Jens Emil", "Clausen", "Jens Emil", "Jens-EmilClausen.jpg"},
            {"Josefine", "Clausen", "Josefine", "JosefineClausen.jpg"},
            {"Benjamin", "Miller", "Ben", "BenjaminMiller.jpg"},
            {"Joss", "Wilson", "Joss", "JossWilson.jpg"},
            {"Kate", "Pelfrey", "Kate", "KatePelfrey"},
            {"Maggie", "Soran", "Maggie", "MaggieSoran.jpg"},
            {"Caleb", "Mulvaney", "Caleb", "CalebMulvaney.jpg"},
            {"Sophia", "Soran", "Sophia", "SophiaSoran.jpg"},
            {"Robert", "Schader", "Robert", "RobertSchader.jpg"},
            {"Holden", "Burns", "Holden", "HoldenBurns.jpg"},
            {"Colin", "Dyson", "Colin", "ColinDyson.jpg"},
            {"Quinn", "Dyson", "Quinn", "QuinnDyson.jpg"},
            {"Zachary", "Power", "Zach", "ZacharyPower"},
            {"Katelyn", "Partridge", "Katelyn", "KatelynPartridge.jpg"},
            {"William", "Ferrel", "Will", "WilliamFerrel"},
            {"Anjali", "Gosal", "Anjali", "AnjaliGosal.jpg"},
            {"Zoe", "Dixon", "Zoe", "ZoeDixon.jpg"},
            {"Jack", "Thompson", "Jack", "JackThompson.jpg"},
            {"Benjamin", "Browder", "Ben", "BenjaminBrowder"},
            {"Kira", "Romberg", "Kira", "KiraRomberg.jpg"},
            {"Richard", "Liu", "Richard", "RichardLiu.jpg"},
            {"Paige", "Newman", "Paige", "PaigeNewman.jpg"},
            {"Lilli", "De Jonghe", "Lilli", "LilliDeJonghe.jpg"},
            {"Heaven", "Torres", "Heaven", "HeavenTorres.jpg"},
            {"Anne", "Thompson", "Anne", "AnneThompson.jpg"},
            {"Noah", "Grady", "Noah", "NoahGrady.jpg"},
            {"Lillian", "Johnson", "Lilli", "LillianJohnson.jpg"},
            {"Sitara", "Reganti", "Sitara", "SitaraReganti.jpg"},
            {"Spencer", "Uppal", "Spencer", "SpencerUppal.jpg"},
            {"Nathan", "Barth", "Nathan", "NathanBarth.jpg"},
            {"Andrew", "Barth", "Andrew", "AndrewBarth.jpg"},
            {"Tabitha", "Gilsdor", "Tabitha", "TabithaGilsdor.jpg"},
            {"Kate", "Clemetson", "Kate", "KateClemetson.jpg"},
            {"Mason", "Clemetson", "Mason", "MasonClemetson.jpg"},
            {"Mason", "Togliatti", "Mason", "MasonTogliatti.jpg"},
            {"Angelina", "Togliatti", "Angelina", "AngelinaTogliatti"},
            {"Jack", "Ditton", "Jack", "JackDitton.jpg"},
            {"Bryce", "Stormo", "Bryce", "BryceStormo.jpg"},
            {"Samantha", "Herrera", "Samantha", "SamanthaHerrera.jpg"},
            {"Mateo", "Carmona", "Mateo", "MateoCarmona.jpg"},
            {"Leila", "Moassessi", "Leila", "LeilaMoassessi.jpg"},
            {"Samuel", "Browder", "Samuel", "SamuelBrowder.jpg"},
            {"Vera", "Ovan der Linden", "Vera", "VeraOvan-der-Linden"},
            {"Sophie", "Najjar", "Sophie", "SophieNajjar.jpg"},
            {"Nhi", "Phan", "Nhi", "NhiPhan.jpg"},
            {"Misha", "Sekhon", "Misha", "MishaSekhon.jpg"},
            {"Adeline", "Guinasso", "Adeline", "AdelineGuinasso.jpg"},
            {"Monroe", "Eads", "Monroe", "MonroeEads.jpg"},
            {"Abigail", "Napoli", "Abigail", "AbigailNapoli.jpg"},
            {"Beatrice", "Liwanag", "Beatrice", "BeatriceLiwanag.jpg"},
            {"Keatyn", "Kurtz", "Keatyn", "KeatynKurtz.jpg"},
            {"Emma", "Sapp", "Emma", "EmmaSapp.jpg"},
            {"Natalie", "Burke", "Natalie", "NatalieBurke.jpg"},
            {"Savannah", "Jukes", "Savannah", "SavannahJukes.jpg"},
            {"Bryn", "Rogoff", "Bryn", "BrynRogoff.jpg"},
            {"Allison", "Baugh", "Allison", "AllisonBaugh"},
            {"Benjamin", "Ferrell", "Benjamin", "BenjaminFerrell.jpg"},
            {"Ava", "Wohletz", "Ava", "AvaWohletz.jpg"},
            {"McKenna", "Kiely", "McKenna", "McKennaKiely.jpg"},
            {"Carter", "Burns", "Carter", "CarterBurns.jpg"},
            {"Hayley", "Burns", "Hayley", "HayleyBurns.jpg"},
            {"Geneva", "Adams", "Geneva", "GenevaAdams.jpg"},
            {"Katherine", "Kilbourn", "Katherine", "KatherineKilborn.jpg"},
            {"Lauren", "Sherven", "Lauren", "LaurenSherven.jpg"},
            {"Emerson", "Evans", "Emerson", "EmersonEvans.jpg"},
            {"Milana", "Gangloff", "Milana", "MilanaGangloff.jpg"},
            {"Shaun", "Greene", "Shaun", "ShaunGreene.jpg"},
            {"Harper", "Westfall", "Harper", "HarperWestfall.jpg"},
            {"Luca", "Westfall", "Luca", "LucaWestfall.jpg"},
            {"Nanki", "Sandhu", "Nanki", "NankiSandhu.jpg"},
            {"Bradley", "Joyer", "Bradley", "BradleyJoyer.jpg"},
            {"Ngoc", "Tran", "Ngoc", "NgocTran.jpg"},
            {"Chenkai", "Hong", "Chenkai", "ChenkaiHong.jpg"},
            {"Keira", "Brodsky", "Keira", "KeiraBrodsky.jpg"},
            {"Jack", "Jaferian", "Jack", "JackJaferian.jpg"},
            {"Sofia", "Jaferian", "Sofia", "SofiaJaferian.jpg"},
            {"Warren", "Strominger", "Warren", "WarrenStrominger.jpg"},
            {"Sydney", "Strominger", "Sydney", "SydneyStrominger.jpg"},
            {"Jeremy", "Gupta", "Jeremy", "JeremyGupta.jpg"},
            {"Josiann", "Trainor", "Josiann", "JosiannTrainor.jpg"},
            {"William", "Dolan", "William", "WilliamDolan.jpg"},
            {"Huxley", "McKenzie", "Huxley", "HuxleyMcKenzie.jpg"},
            {"Ava", "Heaphy", "Ava", "AvaHeaphy.jpg"},
            {"Owen", "Heahpy", "Owen", "OwenHeaphy.jpg"},
            {"Ayden", "Morgan", "Ayden", "AydenMorgan.jpg"},
            {"Parsa", "Valdez", "Parsa", "ParsaValdez.jpg"},
            {"Rhys", "Ferrito", "Rhys", "RhysFerrito.jpg"},
            {"Hannah", "Joyer", "Hannah", "HannahJoyer.jpg"},
            {"Loz", "McKenzie", "Loz", "LozMcKenzie.jpg"},
            {"Carrie", "Sarkissian", "Carrie", "CarrieSarkissian.jpg"},
            {"Tristan", "Schuler", "Tristan", "TristanSchuler.jpg"},
            {"Ryan", "Sherven", "Ryan", "RyanSherven.jpg"},
            {"Eli", "Benna", "Eli", "EliBenna.jpg"},
            {"Nathan", "Brodsky", "Nathan", "NathanBrodsky.jpg"},
            {"Orhan", "Tosun", "Orhan", "OrhanTosun.jpg"},
            {"Kaidan", "Collins", "Kaidan", "KaidanCollins.jpg"},
            {"Michael", "Skaria", "Michael", "MichaelSkaria.jpg"},
            {"Rhea", "Skaria", "Rhea", "RheaSkaria.jpg"},
            {"Brayden", "Uppal", "Brayden", "BraydenUppal.jpg"},
            {"Qingyang", "Wang", "Qingyang", "QingyangWang.jpg"},
            {"Heath", "Fellows", "Heath", "HeathFellows.jpg"},
            {"Gysel", "Najjar", "Gysel", "GyselNajjar.jpg"},
            {"William", "Adams", "William", "WilliamAdams.jpg"},
            {"Trevor", "Schuler", "Trevor", "TrevorSchuler.jpg"},
            {"Tasha", "Schuler", "Tasha", "TashaSchuler.jpg"},
            {"Justin", "Sloyan", "Justin", "JustinSloyan.jpg"},
            {"Forrest", "Gangloff", "Forrest", "ForrestGangloff.jpg"},
            {"Giuliana", "Hovenic", "Giuliana", "GiulianaHovenic.jpg"},
            {"Zach", "Rogoff", "Zach", "ZachRogoff.jpg"},
            {"Kiran", "Vashishta", "Kiran", "KiranVashishta.jpg"},
            {"Charles", "Schader", "Charles", "CharlesSchader.jpg"},
            {"Richard", "Henriksen", "Richard", "RichardHenriksen.jpg"},
            {"Novella", "Segrest", "Novella", "NovellaSegrest.jpg"},
            {"Paige", "Johnson", "Paige", "PaigeJohnson.jpg"},
            {"Debra", "Lehr", "Debra", "DebraLehr.jpg"},
            {"Oscar", "Anderson", "Oscar", "OscarAnderson.jpg"},
            {"Ulysses", "Anderson", "Ulysses", "UlyssesAnderson.jpg"},
            {"Cole", "Ashtonni", "Cole", "ColeAshtonni.jpg"},
            {"John", "Baker", "John", "JohnBaker.jpg"},
            {"Henry", "Berston", "Henry", "HenryBerston.jpg"},
            {"Ava", "Carter", "Ava", "AvaCarter.jpg"},
            {"Samuel", "Carter", "Samuel", "SamuelCarter.jpg"},
            {"Addison", "Clark", "Addison", "AddisonClark.jpg"},
            {"Jackson", "Cowles", "Jackson", "JacksonCowles.jpg"},
            {"Addison", "Davis", "Addison", "AddisonDavis.jpg"},
            {"Annika", "Demers", "AnnikaDemers.jpg"},
            {"Jay", "Dhingra", "Jay", "JayDhingra.jpg"},
            {"Kara", "Dhingra", "Kara", "KaraDhingra.jpg"},
            {"Jane", "Dolan", "Jane", "JaneDolan.jpg"},
            {"Cole", "Dunham", "Cole", "ColeDunham.jpg"},
            {"Anna", "Espinosa", "Anna", "AnnaEspinosa.jpg"},
            {"Violet", "Ferrell", "Violet", "VioletFerrell.jpg"},
            {"Lily", "Flynn", "Lily", "LilyFlynn.jpg"},
            {"Noah", "Gaunt", "Noah", "NoahGaunt.jpg"},
            {"Eli", "Gorelick", "Eli", "EliGorelick.jpg"},
            {"Morgan", "Hertz", "Morgan", "MorganHertz.jpg"},
            {"Morgan", "Hurtz", "Morgan", "MorganHurtz.jpg"},
            {"Hannah", "Hutter", "Hannah", "HannahHutter.jpg"},
            {"Caroline", "Jennings", "Caroline", "CarolineJennings.jpg"},
            {"Krishna", "Kamath", "Krishna", "KrishnaKamath.jpg"},
            {"Elizabeth", "Kenney", "Elizabeth", "ElizabethKenny.jpg"},
            {"Kaylee", "Kirkwood", "Kaylee", "KayleeKirkwood.jpg"},
            {"Carly", "Kotlicky", "Carly", "CarlyKotlicky.jpg"},
            {"Matthew", "Latterell", "Matthew", "MatthewLatterell.jpg"},
            {"Harper", "Lopiccolo", "Harper", "HarperLopiccolo.jpg"},
            {"Scarlett", "Lopiccolo", "Scarlett", "ScarlettLopiccolo.jpg"},
            {"Catherine", "Lovely", "Catherine", "CatherineLovely.jpg"},
            {"Cecily", "Monroe", "Cecily", "CecilyMonroe.jpg"},
            {"Piper", "Morgan", "Piper", "PiperMorgan.jpg"},
            {"Olivia", "Morrison", "Olivia", "OliviaMorrison.jpg"},
            {"Jilliane", "Mueller", "Jilliane", "JillianeMueller.jpg"},
            {"Mac", "Nelson", "Mac", "MacNelson.jpg"},
            {"Breanna", "Pendley", "Breanna", "BreannaPendley.jpg"},
            {"Macallan", "Polk", "Macallan", "MacallanPolk.jpg"},
            {"Murron", "Polk", "Murron", "MurronPolk.jpg"},
            {"Brynn", "Ravazzini", "Brynn", "BrynnRavazzini.jpg"},
            {"Ibby", "Rodriguez", "Ibby", "IbbyRodriguez.jpg"},
            {"Defne", "Sancak", "Defne", "DefneSancak.jpg"},
            {"Meric", "Sancak", "Meric", "MericSancak"},
            {"Arya", "Sekhon", "Arya", "AryaSekhon.jpg"},
            {"Milin", "Sekhon", "Milin", "MilinSekhon.jpg"},
            {"Holt", "Silver", "Holt", "HoltSilver.jpg"},
            {"Julian", "Sloyan", "Julian", "JulianSloyan.jpg"},
            {"Jacob", "Soleman", "Jacob", "JacobSoleman.jpg"},
            {"Thara", "Sundaram", "Thara", "TharaSundaram"},
            {"Michael", "Svetich", "Michael", "MichaelSvetich.jpg"},
            {"Adi", "Venner", "Adi", "AdiVenner.jpg"},
            {"Adam", "Vort", "Adam", "AdamVort.jpg"},
            {"Lauren", "Vort", "Lauren", "LaurenVort.jpg"},
            {"Dominic", "Wakeman", "Dominic", "DominicWakeman.jpg"},
            {"Alex", "Zhang", "Alex", "AlexZhang.jpg"},
            {"Ian", "Zhaoyunt", "Ian", "IanZhaoyunt.jpg"},
            {"Irsa", "Zhou", "Irsa", "IrsaZhou.jpg"}
    };

}
